<?php

declare(strict_types=1);

namespace App\Ai\Agents;

use Carbon\Carbon;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Promptable;
use Laravel\Ai\Responses\AgentResponse;
use Laravel\Ai\Responses\Data\Meta;
use Laravel\Ai\Responses\Data\Usage;

/**
 * Deterministic "fake" agent used when no AI provider is configured.
 * Returns plausible structured output without making HTTP calls.
 */
class FakeSchedulePlannerAgent implements Agent, HasStructuredOutput
{
    use Promptable;

    /**
     * Constructor.
     */
    public function __construct(
        public readonly string $storeName,
        public readonly string $periodStart,
        public readonly string $periodEnd,
    ) {}

    /**
     * Stub instructions (unused for the fake agent).
     */
    public function instructions(): string
    {
        return 'Return a deterministic schedule intent.';
    }

    /**
     * Build the structured schema for the planner output.
     *
     * @return array<string, mixed>
     */
    public function schema(JsonSchema $schema): array
    {
        return \App\Ai\Concerns\PlannerOutputSchema::build($schema);
    }

    /**
     * Bypass the HTTP path. Return a deterministic AgentResponse.
     */
    public function prompt(
        string $prompt,
        array $attachments = [],
        mixed $provider = null,
        string|null $model = null,
        int|null $timeout = null,
    ): AgentResponse {
        $start = Carbon::createFromFormat('Y-m-d', $this->periodStart);
        $end = Carbon::createFromFormat('Y-m-d', $this->periodEnd);
        $rows = [];
        for ($d = $start->copy(); $d->lte($end); $d->addDay()) {
            $dow = (int) $d->format('N');
            $isWeekend = $dow >= 6;
            $rows[] = [
                'date' => $d->format('Y-m-d'),
                'start_time' => $isWeekend ? '11:00' : '10:00',
                'end_time' => $isWeekend ? '20:00' : '18:00',
                'required_employee_count' => $isWeekend ? 2 : 1,
                'role_label' => null,
                'note' => 'Generated by FakeSchedulePlannerAgent',
            ];
        }

        $payload = [
            'intent' => 'create_or_update_schedule',
            'understanding' => "Generated a draft schedule for {$this->storeName} from {$this->periodStart} to {$this->periodEnd} based on the prompt.",
            'warnings' => ['No AI provider configured; using deterministic fake output.'],
            'shift_requirements' => $rows,
        ];

        return new AgentResponse(
            'fake-' . \bin2hex(\random_bytes(8)),
            \json_encode($payload, \JSON_THROW_ON_ERROR),
            new Usage(0, 0, 0, 0, 0),
            new Meta('fake', 'fake'),
        );
    }
}
